### ISSUE TITLE
Issue with portion of theme after update (3/7/19)

### ISSUE THREAD

**Issue by TheVelvetDruid** [PlusInsta/discord-plus#11]
Just had an update for Discord (3/7/19 @ 10:20PM Est.) and afterwards the side navigation for server lists is no longer stylized.
![themeissue](https://user-images.githubusercontent.com/27750853/54005736-8a854d80-4128-11e9-8cb9-a4fa868cd314.png)

**Comment by PlusInsta** [comment]
Fixed by 57b14bb.

**Comment by PlusInsta** [comment]
Accidentally referenced the wrong commit (I was looking at the parent). The correct commit is 88ac5f9.
