### ISSUE TITLE
Wrong aspect for the drag and drop dialog box

### ISSUE THREAD

**Issue by kden1337** [PlusInsta/discord-plus#20]
**Describe the bug**
Wrong aspect for the drag and drop dialog box.

**To Reproduce**
1. Drag and drop an image or whatever in a discord server and that box will pop up.
2. See error.

**Expected behavior**
The box to fit the outline.

**Screenshots**
https://imgur.com/jcc7Cb3

**Additional context**
I am on a 16:10 monitor (1680x1050).

**Comment by PlusInsta** [comment]
I can reproduce only when the language isn't set to English.
Additionally, this happens outside of my theme.
![Screenshot](https://cdn.discordapp.com/attachments/565594764494503937/618423959620157440/Screenshot_2019-09-03_at_14.35.43.png)

Generally speaking, I don't "fix" Discord's stuff unless it's critical for usability as it may end up negatively affecting the theme in the future once it's fixed. [Please report this to Discord themselves instead.](https://support.discordapp.com/hc/en-us/articles/115000465492-How-to-Report-Bugs)

I'll go ahead and mark this issue as invalid.
