### ISSUE TITLE
Option for round icons

### ISSUE THREAD

**Issue by petitbambi** [PlusInsta/discord-plus#34]
I've posted here before and am endlessly grateful you listened to my input about the light theme.
It's perfect, thank you so much ! 

I noticed in one of the latest releases the avatars for both servers and members have turned square and its caused by the fact now the border radius of ALL elements is controlled by a single variable.
I really don't want square avatars but I also don't want the entirety of discord to be completely rounded to a circle - if you're not able/willing to make it a separate option in the public releases for everyone, I'd at least love to know which piece of the code affects this (I've been pokin at the source code file attempting to edit it back with no luck)

Ideally I'd love for the server avatars to stay round while idle and square when a server is opened, while the chat / direct message ones stay round with no changes so if it's possible to remove the part of the code that causes them to be in 1 state and connected to the rest of the elements it would be perfect just to know how to do that myself. 

I also have had to poke in the source code file before due to the fact the backgrounds are set to cover with an !important tag, and I think it would be useful for the public release to allow people to switch between cover and repeat/pattern bgs.

As always wonderful work on this theme and thank you in advance for the help !

**Comment by PlusInsta** [comment]
This is definitely doable by separating the border-radius for profile pictures from the border-radius for everything else, although it'd take a local theme file update if I rolled it out.
The server icons, I'm not too sure. Last I checked, Discord's animation for them turning square and back to round was controlled by a mask, and to make them use my theme's border radius, I had to do away with that mask entirely.
As for the background, it's probably as easy as making the cover/repeat thing a variable, but once again, it'd take an update to everyone's theme file.

@Notiphiliac might be able to help you more.

**Comment by Notiphiliac** [comment]
The border radii are something you'll have to do locally. You have to delete them from the main border radius chunk in the source code file since the !important there makes them unchangeable.
For avatars: 
    in chat: .avatar-1BDn8e
    sidebar: .avatar-VxgULZ
For servers: If you don't mind them only being square while selected (usually they become square when hovered as well) then having two different pieces of code will help you with that:
.wrapper-25eVIn foreignObject {border-radius: 50%; transition-duration: 0.7s;}
.bd-guild.bd-selected .wrapper-25eVIn foreignObject  { border-radius: var(--dplus-border-radius!important; }
If you need any additional help with this, don't be shy to comment.

**Comment by petitbambi** [comment]
Thank you so much !
I was able to revert the icons back to circles editing out the .avatar code and adding the .wrapper code makes the server list icons permanent circles, but regardless of where I put the .bd-guild code it either breaks all other elements or doesn't do anything (I tried replacing the existing bit of code, editing it out and adding this in but in most cases it just makes all code after it not work or shows no difference at all) but I might just be missing something else I need to change in order for it to work ?

I'm guessing that it's not possible to remove the part of the code that gets rid of the mask without it removing the borders on ALL elements (if removing it would just revert the avatars to their original look and animations that would be perfect, but I don't want it to mess up anything else) 

I'd love it if it was possible for the hover animation to stay in too but I also don't wanna bother if its a lot of work - you've already been a great help and I'm grateful for the response !

**Comment by PlusInsta** [comment]
[You're welcome.](https://github.com/PlusInsta/discord-plus/releases/tag/v2.4)
