### ISSUE TITLE
Difficulty understanding how to import fonts

### ISSUE THREAD

**Issue by MinxterYT** [PlusInsta/discord-plus#35]
Title basically describes my issue perfectly

**Comment by PlusInsta** [comment]
I am already working on 2.4.0 which has a detailed description in the master file.

**Comment by MinxterYT** [comment]
ty for the fast response for now is there any way for me to do it easily. Currently reading this:
https://developers.google.com/fonts/docs/getting_started
will that answer my question

**Comment by MinxterYT** [comment]
I got my font working 👍
