### ISSUE TITLE
User Avatar covers Text

### ISSUE THREAD

**Issue by Goolespie** [PlusInsta/discord-plus#37]
The avatar for a user covers the text and name of the user that sends a text

**To Reproduce**
1. Any text in both DM's and servers is covered. No real steps involved

**Expected behavior**
In the photos it looks completely normal and doesnt cover anything

**Screenshots**

![problem](https://user-images.githubusercontent.com/70617258/91926251-2e4dba80-ed1a-11ea-8e8f-2bf54f9f6368.PNG)

**Comment by Notiphiliac** [comment]
Has to do with your font size, if it's not set to the typical 16px, it causes the avatars to cover some of the text. An actual fix to this will be coming soon.

**Comment by Notiphiliac** [comment]
Updated the theme, should be fine whether or not you changed your font size within the next few minutes.
