### ISSUE TITLE
Dark sidebar doesn't really work

### ISSUE THREAD

**Issue by ribkix** [PlusInsta/discord-plus#38]
**Describe the bug**
As we all know, a new feature with the appearance has been added to Discord recently, being able to have a light theme but toggable dark sidebar. But this doesn't look well on Discord Plus.

**To Reproduce**
1. Go to 'User Settings'
2. Click on 'Appearance'
3. Scroll down to 'Dark Sidebar' and toggle it
4. See that the sidebar isn't actually dark

**Expected behavior**
Like everyone, I would expect a dark sidebar.

**Screenshots**
![image](https://user-images.githubusercontent.com/42357978/95001653-37a59d80-05cc-11eb-8253-57fad4b8af0e.png)
(Servers List)
![image](https://user-images.githubusercontent.com/42357978/95001673-691e6900-05cc-11eb-842f-b04c8fc95e1b.png)
(Here the sidebar is just totally white)

**Additional Context**
I am running this using Stylus on chrome browser inside Chrome OS.

**Comment by Notiphiliac** [comment]
Thank you for pointing this out. I've never tested out light mode with dark sidebar so it's easy to miss stuff like this. I've already fixed it and am about to update the theme.
