### ISSUE TITLE
Blur doesn't seem to work

### ISSUE THREAD

**Issue by ASOwnerYT** [PlusInsta/discord-plus#44]
**Describe the bug**
The `--dplus-blur-scale` option doesn't seem to do anything, and nothing in the UI is blurred, not even the background.

**To Reproduce**
1. Look at the UI in the screenshot below. Nothing is blurred.
2. Change the `--dplus-blur-scale` to 1000, which should increase the blur, but it doesn't

**Expected behavior**
At least, the background should be blurred. If different parts of the UI would be blured different amounts, like a glass effect, that would be even better.

**Additional context**
The only things I have changed is `--dplus-background`, `--dplus-accent-ui`, and `--dplus-accent-ui-hover`. I'm using Xwayland on Garuda Linux.

**Comment by PlusInsta** [comment]
![image](https://user-images.githubusercontent.com/38794586/123506908-ef04a780-d666-11eb-891f-4efbcef44baa.png)
Closing as invalid. Make sure your graphics card supports blur functions.

**Comment by ASOwnerYT** [comment]
1. The blur demo works perfectly, and also it's the exact same result with X11 and Wayland, so I can confirm both my desktop environment and graphics card supports Chromium's filter properties.
2. Didn't really see much point of creating a screenshot, as the description should be enough. I couldn't find anything that had a blur effect in Discord (until just now, I found that the right click menu had blur).
3. Oh I thought the background was supposed to be blurred or something lol. Can we turn this into a feature request to add an option to blur the background, please? Also, do you know any themes like this one but with frosted glass? Thanks.
