### ISSUE TITLE
Theme doesn't load; Probably new domain issue

### ISSUE THREAD

**Issue by Spacelag** [PlusInsta/discord-plus#45]
**Describe the bug**
Literally just doesn't load. Other themes work fine. I'm guessing it has to do with the new domain / homepage commit that just happened

**To Reproduce**
1. Activate Theme in BD
2. See error

**Expected behavior**
Theme loads

**Screenshots**
https://cdn.discordapp.com/attachments/406431018069786636/859069240992071690/unknown.png

**Comment by PlusInsta** [comment]
I moved domains. Download the latest release [here](https://github.com/PlusInsta/discord-plus/releases)
