### ISSUE TITLE
blur effect box background?

### ISSUE THREAD

**Issue by allaze-eroler** [PlusInsta/discord-plus#46]
hello, i'm been messing around with your theme, i was surprised there is a blur effect but it's not working... so, my question is how do i enable it? i actually wanted to have all the black or white box blurring the background of my choice.

ps: wouldn't be better if you upload the full FAQ on your github rather than on discord?

**Comment by Notiphiliac** [comment]
I might update the FAQ on Github soon, but the blur effect only works on pop-outs and modals. Ex: Behind the profile pop-out after clicking a username and the entire background behind the larger profile modal. It does not affect all parts of the theme.
