### ISSUE TITLE
misplaced new message bar.

### ISSUE THREAD

**Issue by allaze-eroler** [PlusInsta/discord-plus#47]
**Describe the bug**
the new message bar is wrongly placed...

**To Reproduce**
wait until a chat got a new message, you will be able to see this happening.

**Expected behavior**
it should be placed between 2 text bubbles.

**Screenshots**
![image](https://user-images.githubusercontent.com/6775478/123840828-21383280-d90f-11eb-8fd0-6d448281bed8.png)

**Additional context**
i checked your code source, i realised that ---new-messages-bar code is not present in your code source.

**Comment by Notiphiliac** [comment]
In the source code it is listed by its class, not the id, .divider-3_HH5L. It could be placed between the two bubbles and I had it like that in the past, but everyone complained about a small gap in the middle of the text bubble. If you find a fix yourself, feel free to submit a pull request. Discord does not support these text bubbles so it makes it very hard to get around.

**Comment by allaze-eroler** [comment]
ok, i think i found what is wrong about it, i used an example from this theme https://github.com/CapnKitten/BetterDiscord/tree/master/Themes/Translucence/ because it have the right placement of new message bar...
all you need to do is change the exact portion of code from: 

.divider-3_HH5L.isUnread-3Ef-o9.beforeGroup-1rH1F0 {
    top: 0 !important;
}

and then, you will be able to change it with this: 

.divider-3_HH5L.isUnread-3Ef-o9.beforeGroup-1rH1F0 {
    top: 32px !important;
}
that explain why the new message bar were in the wrong position.

i hope that will help you out!

**Comment by allaze-eroler** [comment]
ok, i think i found what is wrong about it, i used an example from this theme https://github.com/CapnKitten/BetterDiscord/tree/master/Themes/Translucence/ because it have the right placement of new message bar...
all you need to do is change the exact portion of code from: 

.divider-JfaTT5, .container-3RCQyg {
    margin-top: 0 !important;
}

.divider-3_HH5L.isUnread-3Ef-o9.beforeGroup-1rH1F0 {
    top: 0 !important;
}

and then, you will be able to change it with this: 

.divider-JfaTT5, .container-3RCQyg {
    margin-top: -1px !important;
}

.divider-3_HH5L.isUnread-3Ef-o9.beforeGroup-1rH1F0 {
    top: 32px !important;
}

here the result:
![image](https://user-images.githubusercontent.com/6775478/123852129-44b5aa00-d91c-11eb-837a-e642db78f077.png)


that explain why the new message bar were in the wrong position.

i hope that will help you out!

**Comment by allaze-eroler** [comment]
i made a pull request for the fix i made.

**Comment by PlusInsta** [comment]
As the fix has been merged, I'm closing this issue.
