### ISSUE TITLE
Additional Blur Options (Like W11 Acrylic)

### ISSUE THREAD

**Issue by iRhysLee** [PlusInsta/discord-plus#51]
I'd love for the ability to have additional blur options.
Currently I run the theme with a transparent background, and I'd love to be able to have the background of the Discord elements blurred. 

![discordexample](https://user-images.githubusercontent.com/47948838/128078308-580bb1b5-4323-420e-913e-83a2e413e89e.png)

The screenshot is crude, as I changed the colour of the elements to have them more identifiable; but using it as an example, I'd appreciate the ability to have the all the black and pink elements have a blur option. 

Another option that would be appreciated would be the ability to have the background of Discord have a blur option too so that it blurs what is behind the window.

Thanks for the theme!

**Comment by PlusInsta** [comment]
Intentional because blur in Chromium has a severe performance impact. Additionally, there's tons of bugs that have been reported, such as tooltips having a weird black box and context menus being bugged.
