### ISSUE TITLE
[Feature Request] You can customize basically nothing

### ISSUE THREAD

**Issue by raffel080108** [PlusInsta/discord-plus#52]
**Is your feature request related to a problem? Please describe.**
You can't customize the theme in any way apart from changing the background

**Describe the solution you'd like**
I want it so, that you are able to customize more things, like the accent color or the discord logo image at the top left (for example)

**Describe alternatives you've considered**
There isn't really any other way of doing this.. I already tried replacing the import url with code I had customized but it just breaks the theme

**Comment by raffel080108** [comment]
P.S.: Just to make that clear: I really love the theme and the way you made it with multiple layers so the background and other things don't make it so you can basically not read anything in chat or something at all

**Comment by PlusInsta** [comment]
Have you… have you even checked the file? Are you confusing my theme with something else?

You have to be trolling.

**Comment by raffel080108** [comment]
Stop randomly closing issues, thanks

What do you mean I'm trolling, wtf

**Comment by raffel080108** [comment]
I'm just gonna use another theme if the author is stupid like you and puts off things he is too lazy to add as invalid and trolls lmao

**Comment by PlusInsta** [comment]
There's dozens of variables, you're wrong. I'm not gonna discuss this with an obvious troll.

Reopen the issue again and I'm blocking you.

**Comment by PlusInsta** [comment]
Actually, let me just spell this out for you, because I think you genuinely just don't know. If you do, I'm the clown here.

1: FEATURE REQUEST implies I haven't added this. I have put hundreds, if not thousands of hours into making this theme, and you telling me all you can do is change the background will be taken as a personal insult to my work.

2: You could've easily just called this a bug report or opened a support ticket in my server, but you chose to make an issue here on GitHub.

3: There's no way you're so oblivious that you think I haven't implemented any of the things you mention. You can clearly see it in the theme file you've downloaded. 

Give me one reason I should believe you aren't trolling.

**Comment by raffel080108** [comment]
Stop calling me a troll please.

And sorry, it was my bad (I didn't mean to be impolite btw, I was just a big angry)
I just redownloaded the theme to check and now the file looks different than before (Like accually)
I don't know what happened there, maybe I accidently deleted some stuff on the bottom when changing the background

Sorry if I bothered you :)

**Comment by raffel080108** [comment]
Then continue calling me a troll I guess, I really don't care. And if you block my account on here I can just make a new one, so just stop threatning people with that, lol

Anyways, have a nice day

**Comment by PlusInsta** [comment]
> Then continue calling me a troll I guess, I really don't care. And if you block my account on here I can just make a new one, so just stop threatning people with that, lol
> 
> Anyways, have a nice day

And now you resort to threats.

Fuck off.

**Comment by PlusInsta** [comment]
> I don't know what happened there, maybe I accidently deleted some stuff on the bottom when changing the background

If that's what really happened, I figure I owe you an apology for being a major ass just now. Though I doubt you care at this point, it's the least I can do.

PS: Double posting makes it easy for me to miss your posts. Each email I get only shows one post.
